[program:quizly_gunicorn]
user=root
directory=/var/www/myproject/src/ # Bei mir: /home/davidhannemanndev/projects/Quizly
command=/home/davidhannemanndev/projects/Quizly/env/bin/gunicorn django_chat_app.wsgi:application --bind 127.0.0.1:8000 --workers 3
django_chat_app.sock django_chat_app.wsgi:application
autostart=true
autorestart=true
stdout_logfile=/var/log/Quizly/gunicorn.log
stderr_logfile=/var/log/Quizly/gunicorn.err.log
